/**
 * Generated by tsnapi — public API snapshot of `unplugin-jdoss/esbuild`
 */
// #region Variables
export declare const module.exports: typeof Starter.esbuild;
// #endregion

// #region Default Export
declare const _default: typeof Starter.esbuild;
export default _default
// #endregion