/**
 * Generated by tsnapi — public API snapshot of `unplugin-jdoss/farm`
 */
// #region Variables
export declare const module.exports: typeof Starter.farm;
// #endregion

// #region Default Export
declare const _default: typeof Starter.farm;
export default _default
// #endregion