/**
 * Generated by tsnapi — public API snapshot of `unplugin-jdoss`
 */
// #region Interfaces
export interface Options {
  localFullPath: string;
  access: string;
  secret: string;
  site: string;
  cover: boolean;
  timeout: string | number;
  printCdnFile: boolean;
  bucket: string;
  folder: string;
  ignoreRegexp: string;
}
// #endregion

// #region Variables
export declare const Starter: UnpluginInstance<Options, false>;
// #endregion