/**
 * Generated by tsnapi — public API snapshot of `unplugin-jdoss/rolldown`
 */
// #region Variables
export declare const module.exports: typeof Starter.rolldown;
// #endregion

// #region Default Export
declare const _default: typeof Starter.rolldown;
export default _default
// #endregion