/**
 * Generated by tsnapi — public API snapshot of `unplugin-jdoss/rollup`
 */
// #region Variables
export declare const module.exports: typeof Starter.rollup;
// #endregion

// #region Default Export
declare const _default: typeof Starter.rollup;
export default _default
// #endregion