/**
 * Generated by tsnapi — public API snapshot of `unplugin-jdoss/rspack`
 */
// #region Variables
export declare const module.exports: typeof Starter.rspack;
// #endregion

// #region Default Export
declare const _default: typeof Starter.rspack;
export default _default
// #endregion