/**
 * Generated by tsnapi — public API snapshot of `unplugin-jdoss/vite`
 */
// #region Variables
export declare const module.exports: typeof Starter.vite;
// #endregion

// #region Default Export
declare const _default: typeof Starter.vite;
export default _default
// #endregion