/**
 * Generated by tsnapi — public API snapshot of `unplugin-jdoss/webpack`
 */
// #region Variables
export declare const module.exports: typeof Starter.webpack;
// #endregion

// #region Default Export
declare const _default: typeof Starter.webpack;
export default _default
// #endregion